### ISSUE TITLE
No changes detected for my repo

### ISSUE THREAD

**Issue by offirgolan** [html-next/ember-cli-changelog#21]
Hi there! 

For some reason, no changes are detected for [my repo](https://github.com/offirgolan/ember-cp-validations/commits/master). Any ideas what this?

**Comment by runspired** [comment]
Almost all of your commits follow no style guide, you'd need to implement a custom filter.

**Comment by offirgolan** [comment]
Hmmmm that I get, but I dont understand why its happening 😢

**Comment by offirgolan** [comment]
@runspired seems like the filtering issue / the commit style is from PR squashed merges...
