### ISSUE TITLE
Link to definition of "angular style commit messages".

### ISSUE THREAD

**Issue by rwjblue** [html-next/ember-cli-changelog#3]
I'm not terribly familiar with what the exact format is for these messages....

**Comment by runspired** [comment]
there are links to all three message style formats (angular, ember, jquery) in the generated `config/changelog.js`, I'll add them to the README along with available hooks on the next release.

**Comment by pixelhandler** [comment]
https://github.com/runspired/ember-cli-changelog/blob/master/config/changelog.js#L13-L16

**Comment by rwjblue** [comment]
FINE, now you are saying I have to actually _read_ something?!!?!? :smiley_cat:

**Comment by runspired** [comment]
:P

**Comment by runspired** [comment]
This is a very rough alpha, but there's a lot of flexibility in what's here and getting this to a 1.0 that supports all major git platforms / style guides with nice fancy hooks won't take long.  I'll try to make you need to read less by then.

**Comment by pixelhandler** [comment]
Angular's commit guidelines are very specific in format, nice. I did't know that Google has a 'Contributor License Agreement ("CLA")' (makes me sad)

**Comment by runspired** [comment]
Their format has the advantage of being easy to parse with lots of delineated information and easy to scan past in a commit log.  Much more verbose than Ember's and faster to skim than jQuery's.

**Comment by runspired** [comment]
The rough way this works without configuration is that PRs/merges are groups and printed to the changelog under "Pull Requests", any commits that are well-formatted to the style guide are also printed under "Commits", this makes it such that by opting in to the style guide during a specific commit, you also opt in to having it in the changelog, meaning that by writing meaningful commits to help your changelog, and that less meaningful commits won't clutter it.

**Comment by runspired** [comment]
Resolved by a helpful PR #4
